version: '2'
services:
  osd1.node3.ceph.wator.xyz:
    image: ceph/daemon
    network_mode: "host"
    volumes:
      - /ceph/conf/etc:/etc/ceph
      - /ceph/storage1/mon:/var/lib/ceph
      - /ceph/storage1/log:/var/log/ceph/
      - /ceph/storage1/osd:/var/lib/ceph/osd
    environment:
      - OSD_TYPE=directory
      - HOSTNAME=[2400:2412:13e0:9d00:2ce:39ff:fece:132]
    command: osd
    restart: 'always'

  osd2.node3.ceph.wator.xyz:
    image: ceph/daemon
    network_mode: "host"
    volumes:
      - /ceph/conf/etc:/etc/ceph
      - /ceph/storage1/mon:/var/lib/ceph
      - /ceph/storage1/log:/var/log/ceph/
      - /ceph/storage2/osd:/var/lib/ceph/osd
    environment:
      - OSD_TYPE=directory
      - HOSTNAME=[2400:2412:13e0:9d00:2ce:39ff:fece:132]
    command: osd
    restart: 'always'
 
  osd3.node3.ceph.wator.xyz:
    image: ceph/daemon
    network_mode: "host"
    volumes:
      - /ceph/conf/etc:/etc/ceph
      - /ceph/storage1/mon:/var/lib/ceph
      - /ceph/storage1/log:/var/log/ceph/
      - /ceph/storage3/osd:/var/lib/ceph/osd
    environment:
      - OSD_TYPE=directory
      - HOSTNAME=[2400:2412:13e0:9d00:2ce:39ff:fece:132]
    command: osd
    restart: 'always'
